# Generated by Django 5.2.7 on 2025-10-30 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state_code', models.CharField(default='18', max_length=10)),
                ('centroid_lat', models.FloatField(blank=True, null=True)),
                ('centroid_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('snapshot_data', models.DateTimeField(auto_now_add=True)),
                ('html_or_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('persondays', models.BigIntegerField(blank=True, null=True)),
                ('households_worked', models.BigIntegerField(blank=True, null=True)),
                ('wages_disbursed', models.BigIntegerField(blank=True, null=True)),
                ('women_pd_pct', models.FloatField(blank=True, null=True)),
                ('sc_pd_pct', models.FloatField(blank=True, null=True)),
                ('st_pd_pct', models.FloatField(blank=True, null=True)),
                ('pending_payments', models.BigIntegerField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='mgnrega.district')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('district', 'year', 'month')},
            },
        ),
    ]
