# Generated by Django 5.2.7 on 2025-10-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgnrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name_en']},
        ),
        migrations.RemoveField(
            model_name='district',
            name='name',
        ),
        migrations.AddField(
            model_name='district',
            name='name_en',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='name_hi',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='name_mr',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
